### ISSUE TITLE
Buttons not showing in the update window

### ISSUE THREAD

**Issue by victorct** [Deadpikle/NetSparkle#44] opened 2018-03-23 21:44 UTC
I have installed the library in my C# project through NuGet, but every time there is an update the buttons to start downloading, to skip, or to remind the user to download later do not show up in the window, making the library impossible to use.

Here is an example of my code:

```
var sparkle = new Sparkle(
                Misc.Util.getUrl() + "/core/windows/agent/appcast.xml",
                Properties.Resources.Befective,
                NetSparkle.Enums.SecurityMode.Unsafe
            );
sparkle.StartLoop(true,true);

```

![how the window looks](https://user-images.githubusercontent.com/26970809/37854574-11826e5c-2eb1-11e8-8337-9f81ce121e4e.png)

**Comment by victorct** [comment] 2018-03-23 21:47
I have already trying resizing the window, and not success, I cloned the project and opened the Designer of that window, and the buttons are not even inside the panel, they are outside.

**Comment by Deadpikle** [comment] 2018-03-25 02:11
Hi @victorct ! Thanks for the report. Not sure what's going on off the top of my head, but I wanted to acknowledge the report and let you know that I'll look at it ASAP. I haven't run into this issue myself, including in the designer view, so that's odd. You wouldn't happen to be using a non-English language for Sparkle, would you? (I've done no research/work on this fork to make sure that the translations work properly. 😅)

**Comment by Deadpikle** [comment] 2018-03-25 02:20
In a quick look at the code, I see nothing that would be hiding the update available button at the very least. My designer view looks fine. The report of cloning the project and having it not work is also strange. I noticed you're running in VMWare Fusion. Any chance this could be causing strange issues?

Could you please tell me what version of .NET you're using? It looks like the sample projects are broken for some reason (grumble grumble) or I'd ask you to try running those too.

**Comment by Deadpikle** [comment] 2018-03-26 00:52
@victorct I fixed the sample projects. Do you mind pulling the latest code and giving one of the samples a try, say, NetSparkleTestAppWPF, to see if the samples work? I was also unable to find any localization related bugs, as the current localizations just modify strings. I'm definitely not seeing the same things you are if the update buttons are outside the current form. Please provide me with the .NET version you are using and any other helpful info (your OS version [in case some version of Windows 10 is broken], etc.) so that I can help you with this issue! Thanks. :)

**Comment by victorct** [comment] 2018-03-27 17:32
Hello @Deadpikle I didn't have time to do what you need yet, I will do it today and give you the info (about the tests and the OS, .NET framework etc.) later.

I will keep you posted.

**Comment by Deadpikle** [comment] 2018-03-27 17:39
No worries! :) Thanks for your patience and willingness to work with me on this. Hopefully we can get to the bottom of it.

Michael Babienco
-----------------
Lead Programmer/Analyst
Center for Innovation and Research in Computing
Southern Adventist University
http://southern.edu/circ
Partner with me on my next adventure: https://babien.co/missions

**Comment by ndreisg** [comment] 2019-06-12 05:58
While the dialog looks fine on my machine, one of my colleagues was recently able to reproduce this strange issue on his machine.
I will try to get Visual Studio on the affected machine and gain some more insight in the next few days.

**Comment by ndreisg** [comment] 2019-06-13 14:09
First thing I found out:
On the affected machine the default (recommended) scaling factor is 150%
When I set it to 100% the buttons are visible.

**Comment by ndreisg** [comment] 2019-06-13 14:28
Enabling the `AutoSize` property on the buttons fixed it.

**Comment by Deadpikle** [comment] 2019-06-15 12:15
@ndreisg Thanks for looking into this! I'll try to push out a bug fix update in the next few days. 🎈

**Comment by Deadpikle** [comment] 2019-06-23 03:57
@ndreisg 
@victorct 
I've uploaded a 0.16.5 build with a bunch of the buttons set to `AutoSize = true`. Please let me know if this fixes your issue, as I've been unable to replicate the bug on my machine.

**Comment by ndreisg** [comment] 2019-06-24 04:58
With the new 0.16.5 version my dialog is much bigger (HideReleaseNotes = true)
Also interesting: I can only increase the size of the dialog at runtime.

**Comment by ndreisg** [comment] 2019-06-24 05:19
Problem seems to be caused by `AutoSize = true` on the dialog itself (the root Form element)

**Comment by Deadpikle** [comment] 2019-06-24 05:21
I hear you. Give me a few minutes, and I'll remove the `AutoSize = true` on the dialog.

**Comment by Deadpikle** [comment] 2019-06-24 05:27
OK, sorry about that. I've pushed 0.16.6 and commit 3920eb4 to remove `AutoSize = true` on the dialogs.

**Comment by Deadpikle** [comment] 2019-12-02 00:11
@victorct @ndreisg Are things working out for you? I never heard from you if things are working ok. I will close this issue, assuming it's resolved, but please comment here if things pop up again or are not working. Thanks!

**Closed by Deadpikle** 2019-12-02 00:11 UTC
Labels: awaiting feedback, bug
